# Generated by Django 2.2.1 on 2019-06-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190519_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='Furniture', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, default='NN', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='num_units',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='TV', max_length=200),
        ),
    ]
